export const actions = {
  quiz: {
    DATA_FETCHING: "QUIZ_DATA_FETCHING",
    DATA_FETCHED: "QUIZ_DATA_FETCHED",
    DATA_FETCHING_ERROR: "QUIZ_DATA_FETCHING_ERROR",
    DATA_SUBMITTED: "QUIZ_DATA_SUBMITTED",
    ANSWER_SELECTED: "QUIZ_ANSWER_SELECTED",
    ANSWER_SUBMITTED: "QUIZ_ANSWER_SUBMITTED",
  },
};
