export const actions = {
  quiz: {
    DATA_FETCHING: "QUIZ_DATA_FETCHING",
    DATA_FETCHED: "QUIZ_DATA_FETCHED",
    DATA_SUBMITTED: "QUIZ_DATA_SUBMITTED",
    ANSWER_SELECTED: "QUIZ_ANSWER_SELECTED",
    ANSWER_SUBMITTED: "QUIZ_ANSWER_SUBMITTED",
    ANSWER_SUBMITTING_ERROR: "QUIZ_ANSWER_SUBMITTING_ERROR",
  },
  adminQuiz: {
    DATA_FETCHING: "ADMIN_QUIZ_DATA_FETCHING",
    DATA_FETCHED: "ADMIN_QUIZ_DATA_FETCHED",
    QUIZ_TOPIC_SUBMITTED: "ADMIN_QUIZ_TOPIC_SUBMITTED",
    FULL_QUIZ_SET_SUBMITTED: "ADMIN_FULL_QUIZ_SET_SUBMITTED",
  },
  result: {
    DATA_FETCHING: "RESULT_DATA_FETCHING",
    DATA_FETCHED: "RESULT_DATA_FETCHED",
  },
};
